"use client";
import { useMemo, useState } from "react";
type Profile="general"|"compute"|"memory";
const profiles:Record<Profile,{label:string;cpu:number;ram:number;note:string}>={general:{label:"Balanceado",cpu:16,ram:64,note:"Aplicaciones web, APIs y servicios mixtos"},compute:{label:"CPU intensivo",cpu:32,ram:64,note:"Procesamiento, CI y cargas paralelas"},memory:{label:"Memoria intensiva",cpu:16,ram:128,note:"JVM, cachés, analítica y datos"}};
const nf=new Intl.NumberFormat("es-DO",{maximumFractionDigits:1});
export default function Home(){
 const[apps,setApps]=useState(20),[replicas,setReplicas]=useState(2),[cpu,setCpu]=useState(.5),[ram,setRam]=useState(1),[storage,setStorage]=useState(500),[growth,setGrowth]=useState(30),[headroom,setHeadroom]=useState(25);const[ha,setHa]=useState(true),[profile,setProfile]=useState<Profile>("general");
 const r=useMemo(()=>{const n=profiles[profile],pods=apps*replicas,f=(1+growth/100)*(1+headroom/100),reqCpu=pods*cpu*f,reqRam=pods*ram*f,usableCpu=n.cpu*.78,usableRam=n.ram*.75,capacity=Math.max(1,Math.ceil(Math.max(reqCpu/usableCpu,reqRam/usableRam))),workers=ha?Math.max(3,capacity+1):Math.max(2,capacity),physical=Math.ceil(storage*(1+growth/100)*(ha?3:2)*1.2);return{pods,reqCpu,reqRam,workers,physical,totalCpu:workers*n.cpu+(ha?12:4),totalRam:workers*n.ram+(ha?48:16),cpuLoad:Math.round(reqCpu/(workers*usableCpu)*100),ramLoad:Math.round(reqRam/(workers*usableRam)*100)}},[apps,replicas,cpu,ram,storage,growth,headroom,ha,profile]);
 const reset=()=>{setApps(20);setReplicas(2);setCpu(.5);setRam(1);setStorage(500);setGrowth(30);setHeadroom(25);setHa(true);setProfile("general")};
 const Field=({label,value,setValue,min,max,step=1,suffix}:{label:string;value:number;setValue:(n:number)=>void;min:number;max:number;step?:number;suffix:string})=><label className="field"><span>{label}</span><div className="input-wrap"><input aria-label={label} type="number" value={value} min={min} max={max} step={step} onChange={e=>setValue(Math.min(max,Math.max(min,Number(e.target.value))))}/><b>{suffix}</b></div></label>;
 return <main><header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark">K</span><span>KubeSize <small>ON-PREM</small></span></a><nav><a href="#metodo">Metodología</a><a href="#supuestos">Supuestos</a><button onClick={reset}>Restablecer</button></nav></header>
 <section className="hero" id="inicio"><div className="eyebrow"><span/>PLANEACIÓN DE CAPACIDAD</div><h1>Dimensiona tu clúster.<br/><em>Sin adivinar.</em></h1><p>Convierte la demanda de tus aplicaciones en una topología Kubernetes on-premise defendible, preparada para crecer y tolerar fallos.</p><div className="hero-stats"><span><b>CPU</b> basada en requests</span><span><b>HA</b> fallo de un nodo</span><span><b>STORAGE</b> réplica incluida</span></div></section>
 <section className="calculator"><div className="panel inputs-panel"><div className="section-heading"><span>01</span><div><h2>Define la demanda</h2><p>Usa requests reales o una estimación conservadora.</p></div></div><div className="form-grid"><Field label="Aplicaciones" value={apps} setValue={setApps} min={1} max={500} suffix="apps"/><Field label="Réplicas promedio" value={replicas} setValue={setReplicas} min={1} max={20} suffix="por app"/><Field label="CPU request promedio" value={cpu} setValue={setCpu} min={.1} max={16} step={.1} suffix="vCPU"/><Field label="RAM request promedio" value={ram} setValue={setRam} min={.1} max={64} step={.1} suffix="GiB"/><Field label="Datos útiles" value={storage} setValue={setStorage} min={10} max={100000} step={10} suffix="GiB"/><Field label="Crecimiento proyectado" value={growth} setValue={setGrowth} min={0} max={200} step={5} suffix="12 meses"/></div>
 <div className="divider"/><div className="section-heading compact"><span>02</span><div><h2>Selecciona la estrategia</h2></div></div><div className="profiles" role="radiogroup">{(Object.keys(profiles) as Profile[]).map(k=><button key={k} className={profile===k?"profile active":"profile"} onClick={()=>setProfile(k)} role="radio" aria-checked={profile===k}><span className="radio"/><b>{profiles[k].label}</b><small>{profiles[k].cpu} vCPU · {profiles[k].ram} GiB</small><p>{profiles[k].note}</p></button>)}</div>
 <div className="toggles"><label><input type="checkbox" checked={ha} onChange={e=>setHa(e.target.checked)}/><span/><div><b>Alta disponibilidad</b><small>3 control planes + capacidad N+1</small></div></label><label className="range"><div><b>Margen operativo</b><small>Para picos y despliegues</small></div><strong>{headroom}%</strong><input aria-label="Margen operativo" type="range" min="10" max="50" step="5" value={headroom} onChange={e=>setHeadroom(Number(e.target.value))}/></label></div></div>
 <aside className="panel results-panel" aria-live="polite"><div className="result-title"><span>RECOMENDACIÓN</span><i>Actualización instantánea</i></div><div className="node-count"><strong>{r.workers}</strong><div><b>nodos worker</b><small>{profiles[profile].cpu} vCPU · {profiles[profile].ram} GiB cada uno</small></div></div><div className="topology"><h3>Topología sugerida</h3><div className="topology-row"><div className="node-icons">{Array.from({length:ha?3:1}).map((_,i)=><span className="node control" key={i}>C</span>)}</div><p><b>{ha?3:1} × Control plane</b><small>4 vCPU · 16 GiB · SSD</small></p></div><div className="topology-row"><div className="node-icons">{Array.from({length:Math.min(r.workers,5)}).map((_,i)=><span className="node worker" key={i}>W</span>)}</div><p><b>{r.workers} × Workers</b><small>{profiles[profile].cpu} vCPU · {profiles[profile].ram} GiB</small></p></div></div>
 <div className="capacity"><div><span>CPU estimada <b>{nf.format(r.reqCpu)} vCPU</b></span><div className="bar"><i style={{width:`${Math.min(r.cpuLoad,100)}%`}}/></div><small>{r.cpuLoad}% de capacidad utilizable</small></div><div><span>RAM estimada <b>{nf.format(r.reqRam)} GiB</b></span><div className="bar"><i style={{width:`${Math.min(r.ramLoad,100)}%`}}/></div><small>{r.ramLoad}% de capacidad utilizable</small></div></div><div className="totals"><div><small>CAPACIDAD BRUTA</small><b>{r.totalCpu} vCPU</b><span>{r.totalRam} GiB RAM</span></div><div><small>ALMACENAMIENTO FÍSICO</small><b>{nf.format(r.physical/1024)} TiB</b><span>{ha?"3 réplicas":"2 réplicas"} + 20% libre</span></div></div><div className="callout"><b>✓ Diseño {ha?"tolerante":"económico"}</b><p>{ha?"Conserva capacidad operativa ante la pérdida de un worker y mantiene quorum del control plane.":"Sin quorum HA. Recomendado solamente para laboratorios o desarrollo."}</p></div></aside></section>
 <section className="method" id="metodo"><div className="eyebrow"><span/>CÓMO CALCULAMOS</div><h2>Capacidad que puedes usar,<br/>no la que dice la etiqueta.</h2><div className="method-grid"><article><b>01</b><h3>Demanda base</h3><p>Multiplicamos aplicaciones, réplicas y requests promedio. El resultado refleja pods activos, no límites teóricos.</p></article><article><b>02</b><h3>Reserva y margen</h3><p>Descontamos recursos para el sistema y añadimos crecimiento más margen para picos, rollouts y mantenimiento.</p></article><article><b>03</b><h3>Tolerancia N+1</h3><p>En alta disponibilidad agregamos capacidad para perder un worker sin comprometer los requests calculados.</p></article></div></section>
 <section className="assumptions" id="supuestos"><div><h2>Supuestos del modelo</h2><p>Una estimación transparente es más útil que una cifra falsa de precisión.</p></div><ul><li>22% de CPU reservado por nodo</li><li>25% de RAM reservada por nodo</li><li>Storage con 20% de espacio libre</li><li>Control plane en nodos dedicados</li><li>Requests representativos</li><li>No incluye GPU ni red</li></ul></section><footer><div className="brand"><span className="brand-mark">K</span><span>KubeSize</span></div><p>Estimación inicial para planeación. Valida con pruebas de carga, observabilidad y requisitos del fabricante.</p><a href="#inicio">Volver arriba ↑</a></footer></main>;
}
