apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dimensionador-k8s
  labels:
    app.kubernetes.io/name: dimensionador-k8s
    app.kubernetes.io/part-of: dimensionador-k8s
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
